version: "3.8"

services:
  # -- NestJS Backend Service (insight-be) --
  insight-be:
    build: ./insight-be
    container_name: insight-be
    ports:
      - "3000:3000"
    volumes:
      - ./insight-be:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "100"
      ### DATABASE ###
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: nestjs_db
      ### SSO ###
      # Google
      GOOGLE_CLIENT_ID: "123-abc.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "secret_google_key"
      GOOGLE_CALLBACK_URL: "http://localhost:3000/auth/google/callback"
      # Apple
      APPLE_SERVICE_ID: "com.your.app.service"
      APPLE_TEAM_ID: "ABCDE12345"
      APPLE_KEY_ID: "ZZZZ9999"
      APPLE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkq...\n-----END PRIVATE KEY-----"
      APPLE_CALLBACK_URL: "http://localhost:3000/auth/apple/callback"
      # JWT
      JWT_SECRET: "..."
      JWT_REFRESH_SECRET: "..."
    command: npm run start:dev
    depends_on:
      - postgres

  # -- Next.js Frontend Service (insight-fe) --
  insight-fe:
    build: ./insight-fe
    container_name: insight-fe
    ports:
      - "3001:3000"
    volumes:
      - ./insight-fe:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      # CHOKIDAR_USEPOLLING: "true"
      # CHOKIDAR_INTERVAL: "1000"
    command: npm run dev
    depends_on:
      - insight-be

  # -- PostgreSQL Database Service --
  postgres:
    image: postgres:16-alpine
    container_name: insight-postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
