import type { Metadata } from "next";
import TopLevelProviders from "@/providers/TopLevelProviders";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TopLevelProviders>{children}</TopLevelProviders>
      </body>
    </html>
  );
}
