// app/layout.tsx
import type { Metadata } from "next";
import { cookies } from "next/headers";
import { jwtDecode } from "jwt-decode";
import TopLevelProviders from "@/providers/TopLevelProviders";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export interface UserPayload {
  publicId: string;
  permissions: string[];
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const token = cookies().get("accessToken")?.value;
  let user: UserPayload | null = null;

  if (token) {
    try {
      user = jwtDecode<UserPayload>(token);
    } catch {
      user = null;
    }
  }

  return (
    <html lang="en">
      <body>
        <TopLevelProviders user={user}>{children}</TopLevelProviders>
      </body>
    </html>
  );
}
