"use client";

import React, { useState, useMemo } from "react";
import { ContentCard } from "@/components/layout/Card";
import DataTable from "@/components/tables/DataTable";

function camelCaseToTitle(str: string): string {
  return str
    .replace(/([A-Z])/g, " $1")
    .replace(/^./, (char) => char.toUpperCase());
}

interface DataTableAutoGeneratedProps<T> {
  data: T[];
}

export function DataTableAutoGenerated<T extends { [key: string]: any }>({
  data,
}: DataTableAutoGeneratedProps<T>) {
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(10);

  const columns = useMemo(() => {
    if (!data || data.length === 0) return [];
    const sampleItem = data[0];

    return Object.keys(sampleItem).map((key) => ({
      key: key as keyof T,
      label: camelCaseToTitle(key),
    }));
  }, [data]);

  console.log(columns);

  return (
    <ContentCard>
      KRULL
      {/* <DataTable
        data={data}
        columns={columns}
        currentPage={currentPage}
        itemsPerPage={itemsPerPage}
        onPageChange={setCurrentPage}
        onItemsPerPageChange={setItemsPerPage}
        onRowClick={(row) => console.log("Clicked row:", row)}
      /> */}
    </ContentCard>
  );
}
