/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	CreateAssignmentInput:{
		dueDate:"DateTime"
	},
	CreateAssignmentSubmissionInput:{
		submittedAt:"DateTime"
	},
	CreateClassInput:{

	},
	CreateEducatorProfileInput:{

	},
	CreateKeyStageInput:{

	},
	CreateLessonInput:{

	},
	CreatePermissionGroupInput:{

	},
	CreatePermissionInput:{

	},
	CreateRoleInput:{

	},
	CreateStudentProfileInput:{

	},
	CreateSubjectInput:{
		relationIds:"RelationIdsInput"
	},
	CreateUserRequestDto:{
		dateOfBirth:"DateTime"
	},
	CreateUserWithProfileInput:{
		dateOfBirth:"DateTime",
		educatorProfile:"CreateEducatorProfileInput",
		studentProfile:"CreateStudentProfileInput"
	},
	CreateYearGroupInput:{
		year:"ValidYear"
	},
	DateTime: `scalar.DateTime` as const,
	FilterInput:{

	},
	FindAllInput:{
		filters:"FilterInput"
	},
	FindOneByInput:{

	},
	IdInput:{

	},
	IdRequestDto:{

	},
	LoginRequest:{

	},
	Mutation:{
		createAssignment:{
			data:"CreateAssignmentInput"
		},
		createAssignmentSubmission:{
			data:"CreateAssignmentSubmissionInput"
		},
		createClass:{
			data:"CreateClassInput"
		},
		createEducatorProfile:{
			data:"CreateEducatorProfileInput"
		},
		createKeyStage:{
			data:"CreateKeyStageInput"
		},
		createLesson:{
			data:"CreateLessonInput"
		},
		createPermission:{
			data:"CreatePermissionInput"
		},
		createPermissionGroup:{
			data:"CreatePermissionGroupInput"
		},
		createRole:{
			data:"CreateRoleInput"
		},
		createStudentProfile:{
			data:"CreateStudentProfileInput"
		},
		createSubject:{
			data:"CreateSubjectInput"
		},
		createTest:{
			data:"CreateSubjectInput"
		},
		createUser:{
			data:"CreateUserRequestDto"
		},
		createUserWithProfile:{
			data:"CreateUserWithProfileInput"
		},
		createYearGroup:{
			data:"CreateYearGroupInput"
		},
		deleteAssignment:{
			data:"IdInput"
		},
		deleteAssignmentSubmission:{
			data:"IdInput"
		},
		deleteClass:{
			data:"IdInput"
		},
		deleteEducatorProfile:{
			data:"IdInput"
		},
		deleteKeyStage:{
			data:"IdInput"
		},
		deleteLesson:{
			data:"IdInput"
		},
		deletePermission:{
			data:"IdInput"
		},
		deletePermissionGroup:{
			data:"IdInput"
		},
		deleteRole:{
			data:"IdInput"
		},
		deleteStudentProfile:{
			data:"IdInput"
		},
		deleteSubject:{
			data:"IdInput"
		},
		deleteYearGroup:{
			data:"IdInput"
		},
		logUserInWithEmailAndPassword:{
			data:"LoginRequest"
		},
		refreshUsersTokens:{

		},
		registerNewUserLocally:{
			data:"CreateUserRequestDto"
		},
		removeUserByPublicId:{
			data:"PublicIdRequestDto"
		},
		updateAssignment:{
			data:"UpdateAssignmentInput"
		},
		updateAssignmentSubmission:{
			data:"UpdateAssignmentSubmissionInput"
		},
		updateClass:{
			data:"UpdateClassInput"
		},
		updateEducatorProfile:{
			data:"UpdateEducatorProfileInput"
		},
		updateKeyStage:{
			data:"UpdateKeyStageInput"
		},
		updateLesson:{
			data:"UpdateLessonInput"
		},
		updatePermission:{
			data:"UpdatePermissionInput"
		},
		updatePermissionGroup:{
			data:"UpdatePermissionGroupInput"
		},
		updatePermissionGroupPermissionsFromArray:{
			data:"SubmitIdArrayByIdRequestDto"
		},
		updatePermissionGroupsForRole:{
			data:"SubmitIdArrayByIdRequestDto"
		},
		updateRole:{
			data:"UpdateRoleInput"
		},
		updateStudentProfile:{
			data:"UpdateStudentProfileInput"
		},
		updateSubject:{
			data:"UpdateSubjectInput"
		},
		updateUserByPublicId:{
			data:"UpdateUserWithProfileInput"
		},
		updateUserRolesFromArray:{
			data:"UpdateUserRolesFromArrayRequestDto"
		},
		updateYearGroup:{
			data:"UpdateYearGroupInput"
		}
	},
	PaginatedGetAllRequestDto:{

	},
	PublicIdRequestDto:{

	},
	Query:{
		getAllAssignment:{
			data:"FindAllInput"
		},
		getAllAssignmentSubmission:{
			data:"FindAllInput"
		},
		getAllClass:{
			data:"FindAllInput"
		},
		getAllEducatorProfile:{
			data:"FindAllInput"
		},
		getAllKeyStage:{
			data:"FindAllInput"
		},
		getAllLesson:{
			data:"FindAllInput"
		},
		getAllPermission:{
			data:"FindAllInput"
		},
		getAllPermissionGroup:{
			data:"FindAllInput"
		},
		getAllRole:{
			data:"FindAllInput"
		},
		getAllStudentProfile:{
			data:"FindAllInput"
		},
		getAllSubject:{
			data:"FindAllInput"
		},
		getAllUsers:{
			data:"PaginatedGetAllRequestDto"
		},
		getAllYearGroup:{
			data:"FindAllInput"
		},
		getAssignment:{
			data:"IdInput"
		},
		getAssignmentBy:{
			data:"FindOneByInput"
		},
		getAssignmentSubmission:{
			data:"IdInput"
		},
		getAssignmentSubmissionBy:{
			data:"FindOneByInput"
		},
		getClass:{
			data:"IdInput"
		},
		getClassBy:{
			data:"FindOneByInput"
		},
		getEducatorProfile:{
			data:"IdInput"
		},
		getEducatorProfileBy:{
			data:"FindOneByInput"
		},
		getKeyStage:{
			data:"IdInput"
		},
		getKeyStageBy:{
			data:"FindOneByInput"
		},
		getLesson:{
			data:"IdInput"
		},
		getLessonBy:{
			data:"FindOneByInput"
		},
		getPermission:{
			data:"IdInput"
		},
		getPermissionBy:{
			data:"FindOneByInput"
		},
		getPermissionGroup:{
			data:"IdInput"
		},
		getPermissionGroupBy:{
			data:"FindOneByInput"
		},
		getPermissionGroupsForRole:{
			data:"IdRequestDto"
		},
		getPermissionsForGroup:{
			data:"IdRequestDto"
		},
		getRole:{
			data:"IdInput"
		},
		getRoleBy:{
			data:"FindOneByInput"
		},
		getRolesForUser:{
			data:"PublicIdRequestDto"
		},
		getStudentProfile:{
			data:"IdInput"
		},
		getStudentProfileBy:{
			data:"FindOneByInput"
		},
		getSubject:{
			data:"IdInput"
		},
		getSubjectBy:{
			data:"FindOneByInput"
		},
		getUserByPublicId:{
			data:"PublicIdRequestDto"
		},
		getUsersRolesAndPermissions:{
			data:"UserPermissionsInput"
		},
		getYearGroup:{
			data:"IdInput"
		},
		getYearGroupBy:{
			data:"FindOneByInput"
		}
	},
	RelationIdsInput:{

	},
	SubmitIdArrayByIdRequestDto:{

	},
	UpdateAssignmentInput:{
		dueDate:"DateTime"
	},
	UpdateAssignmentSubmissionInput:{
		submittedAt:"DateTime"
	},
	UpdateClassInput:{

	},
	UpdateEducatorProfileInput:{

	},
	UpdateKeyStageInput:{

	},
	UpdateLessonInput:{

	},
	UpdatePermissionGroupInput:{

	},
	UpdatePermissionInput:{

	},
	UpdateRoleInput:{

	},
	UpdateStudentProfileInput:{

	},
	UpdateSubjectInput:{
		relationIds:"RelationIdsInput"
	},
	UpdateUserRolesFromArrayRequestDto:{

	},
	UpdateUserWithProfileInput:{
		dateOfBirth:"DateTime",
		educatorProfile:"CreateEducatorProfileInput",
		studentProfile:"CreateStudentProfileInput"
	},
	UpdateYearGroupInput:{
		year:"ValidYear"
	},
	UserPermissionsInput:{

	},
	ValidKeyStage: "enum" as const,
	ValidYear: "enum" as const,
	ID: `scalar.ID` as const
}

export const ReturnTypes: Record<string,any> = {
	AssignmentEntity:{
		class:"ClassEntity",
		createdAt:"DateTime",
		description:"String",
		dueDate:"DateTime",
		id:"ID",
		lesson:"LessonEntity",
		title:"String",
		updatedAt:"DateTime"
	},
	AssignmentSubmissionEntity:{
		assignment:"AssignmentEntity",
		createdAt:"DateTime",
		feedback:"String",
		grade:"String",
		id:"ID",
		student:"StudentProfileDto",
		submissionContent:"String",
		submittedAt:"DateTime",
		updatedAt:"DateTime"
	},
	AuthTokens:{
		accessToken:"String",
		refreshToken:"String"
	},
	ClassEntity:{
		createdAt:"DateTime",
		educators:"EducatorProfileDto",
		id:"ID",
		name:"String",
		students:"StudentProfileDto",
		subject:"SubjectEntity",
		updatedAt:"DateTime",
		yearGroup:"YearGroupEntity"
	},
	DateTime: `scalar.DateTime` as const,
	EducatorProfileDto:{
		createdAt:"DateTime",
		id:"ID",
		staffId:"Float",
		updatedAt:"DateTime"
	},
	KeyStageEntity:{
		createdAt:"DateTime",
		description:"String",
		id:"ID",
		name:"String",
		stage:"ValidKeyStage",
		updatedAt:"DateTime",
		yearGroups:"YearGroupEntity"
	},
	LessonEntity:{
		content:"String",
		createdAt:"DateTime",
		createdBy:"EducatorProfileDto",
		createdById:"ID",
		id:"ID",
		recommendedYearGroups:"YearGroupEntity",
		subject:"SubjectEntity",
		title:"String",
		updatedAt:"DateTime"
	},
	LoginResponse:{
		accessToken:"String",
		refreshToken:"String",
		userDetails:"UserDetails"
	},
	Mutation:{
		createAssignment:"AssignmentEntity",
		createAssignmentSubmission:"AssignmentSubmissionEntity",
		createClass:"ClassEntity",
		createEducatorProfile:"EducatorProfileDto",
		createKeyStage:"KeyStageEntity",
		createLesson:"LessonEntity",
		createPermission:"Permission",
		createPermissionGroup:"PermissionGroup",
		createRole:"Role",
		createStudentProfile:"StudentProfileDto",
		createSubject:"SubjectEntity",
		createTest:"SubjectEntity",
		createUser:"User",
		createUserWithProfile:"User",
		createYearGroup:"YearGroupEntity",
		deleteAssignment:"Boolean",
		deleteAssignmentSubmission:"Boolean",
		deleteClass:"Boolean",
		deleteEducatorProfile:"Boolean",
		deleteKeyStage:"Boolean",
		deleteLesson:"Boolean",
		deletePermission:"Boolean",
		deletePermissionGroup:"Boolean",
		deleteRole:"Boolean",
		deleteStudentProfile:"Boolean",
		deleteSubject:"Boolean",
		deleteYearGroup:"Boolean",
		logUserInWithEmailAndPassword:"AuthTokens",
		refreshUsersTokens:"LoginResponse",
		registerNewUserLocally:"User",
		removeUserByPublicId:"User",
		updateAssignment:"AssignmentEntity",
		updateAssignmentSubmission:"AssignmentSubmissionEntity",
		updateClass:"ClassEntity",
		updateEducatorProfile:"EducatorProfileDto",
		updateKeyStage:"KeyStageEntity",
		updateLesson:"LessonEntity",
		updatePermission:"Permission",
		updatePermissionGroup:"PermissionGroup",
		updatePermissionGroupPermissionsFromArray:"PermissionGroup",
		updatePermissionGroupsForRole:"Role",
		updateRole:"Role",
		updateStudentProfile:"StudentProfileDto",
		updateSubject:"SubjectEntity",
		updateUserByPublicId:"User",
		updateUserRolesFromArray:"User",
		updateYearGroup:"YearGroupEntity"
	},
	Permission:{
		createdAt:"DateTime",
		description:"String",
		id:"ID",
		name:"String",
		permissionGroups:"PermissionGroup",
		roles:"Role",
		updatedAt:"DateTime"
	},
	PermissionDTO:{
		createdAt:"DateTime",
		id:"Float",
		name:"String",
		updatedAt:"DateTime"
	},
	PermissionGroup:{
		createdAt:"DateTime",
		description:"String",
		id:"ID",
		name:"String",
		permissions:"Permission",
		roles:"Role",
		updatedAt:"DateTime"
	},
	Query:{
		getAllAssignment:"AssignmentEntity",
		getAllAssignmentSubmission:"AssignmentSubmissionEntity",
		getAllClass:"ClassEntity",
		getAllEducatorProfile:"EducatorProfileDto",
		getAllKeyStage:"KeyStageEntity",
		getAllLesson:"LessonEntity",
		getAllPermission:"Permission",
		getAllPermissionGroup:"PermissionGroup",
		getAllRole:"Role",
		getAllStudentProfile:"StudentProfileDto",
		getAllSubject:"SubjectEntity",
		getAllUsers:"User",
		getAllYearGroup:"YearGroupEntity",
		getAssignment:"AssignmentEntity",
		getAssignmentBy:"AssignmentEntity",
		getAssignmentSubmission:"AssignmentSubmissionEntity",
		getAssignmentSubmissionBy:"AssignmentSubmissionEntity",
		getClass:"ClassEntity",
		getClassBy:"ClassEntity",
		getEducatorProfile:"EducatorProfileDto",
		getEducatorProfileBy:"EducatorProfileDto",
		getKeyStage:"KeyStageEntity",
		getKeyStageBy:"KeyStageEntity",
		getLesson:"LessonEntity",
		getLessonBy:"LessonEntity",
		getPermission:"Permission",
		getPermissionBy:"Permission",
		getPermissionGroup:"PermissionGroup",
		getPermissionGroupBy:"PermissionGroup",
		getPermissionGroupsForRole:"PermissionGroup",
		getPermissionsForGroup:"Permission",
		getRole:"Role",
		getRoleBy:"Role",
		getRolesForUser:"Role",
		getStudentProfile:"StudentProfileDto",
		getStudentProfileBy:"StudentProfileDto",
		getSubject:"SubjectEntity",
		getSubjectBy:"SubjectEntity",
		getUserByPublicId:"User",
		getUsersRolesAndPermissions:"RolesPermissionsResponse",
		getYearGroup:"YearGroupEntity",
		getYearGroupBy:"YearGroupEntity"
	},
	Role:{
		createdAt:"DateTime",
		description:"String",
		id:"ID",
		name:"String",
		permissionGroups:"PermissionGroup",
		permissions:"Permission",
		updatedAt:"DateTime"
	},
	RoleDTO:{
		createdAt:"DateTime",
		id:"Float",
		name:"String",
		updatedAt:"DateTime"
	},
	RolesPermissionsResponse:{
		permissions:"PermissionDTO",
		roles:"RoleDTO"
	},
	StudentProfileDto:{
		createdAt:"DateTime",
		id:"ID",
		schoolYear:"Float",
		studentId:"Float",
		updatedAt:"DateTime"
	},
	SubjectEntity:{
		createdAt:"DateTime",
		id:"ID",
		name:"String",
		updatedAt:"DateTime",
		yearGroups:"YearGroupEntity"
	},
	User:{
		addressLine1:"String",
		addressLine2:"String",
		city:"String",
		country:"String",
		county:"String",
		createdAt:"DateTime",
		dateOfBirth:"DateTime",
		educatorProfile:"EducatorProfileDto",
		email:"String",
		firstName:"String",
		id:"ID",
		lastName:"String",
		phoneNumber:"String",
		postalCode:"String",
		publicId:"String",
		roles:"Role",
		studentProfile:"StudentProfileDto",
		updatedAt:"DateTime",
		userType:"String"
	},
	UserDetails:{
		permissions:"String",
		publicId:"String"
	},
	YearGroupEntity:{
		createdAt:"DateTime",
		id:"ID",
		keyStage:"KeyStageEntity",
		subjects:"SubjectEntity",
		updatedAt:"DateTime",
		year:"ValidYear"
	},
	ID: `scalar.ID` as const
}

export const Ops = {
query: "Query" as const,
	mutation: "Mutation" as const
}